name: flutter_run_cat
description: It is System monitor only for Linux OS.
publish_to: 'yoehwan@gmail.com' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.3
  flutter_app_indicator:
    git:
      url: https://github.com/yoehwan/flutter_app_indicator.git
      ref: main
  bitsdojo_window: ^0.1.1+1
  tuple: 
  hive: ^2.1.0
  hive_flutter: 
  package_info_plus: ^1.4.2
  yaml: ^3.1.0 
  url_launcher: 
  fluentui_system_icons: ^1.1.169
  reorderables: ^0.5.0
  file_picker: ^4.5.1
  badges: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cat/
